### ISSUE TITLE
Error in story book adding 

### ISSUE THREAD

**Issue by Nethmi96** [bitsoferised/ShareABook_Frontend_v.2#15]
I'm getting an error with status code 500 when trying to add a new book.
![image](https://user-images.githubusercontent.com/44530828/79615910-5cdb4800-8121-11ea-8ccc-291ac8d65332.png)
![image](https://user-images.githubusercontent.com/44530828/79615918-62389280-8121-11ea-8eba-49b85e715908.png)

**Comment by dilinipeirs** [comment]
Please show me the server error shown in server log..

in the second picture, you have just put the URL in the browser.. which sends a GET request to the server.. but  add book function works on POST request.. use postman or similar app to send POST and other requests.

**Comment by Nethmi96** [comment]
![image](https://user-images.githubusercontent.com/44530828/79632122-ec611500-817a-11ea-9892-7c7c615b4938.png)
![image](https://user-images.githubusercontent.com/44530828/79632128-f71baa00-817a-11ea-80c8-df69a8e3d6c3.png)

**Comment by dilinipeirs** [comment]
I am looking into this. Will take some time

**Comment by dilinipeirs** [comment]
this error you mentioned is resolved.

But please look into these.

1. server returns false and the success alert (green) in shown

2. I believe you have hard coded the subject names? Because of this, the book is not getting added because the subject names in the database are different. Use the API doc and retrieve the AL subjects accordingly. Then when you are getting the subjects from the database, the book will be added successfully.
eg. 
![image](https://user-images.githubusercontent.com/28673959/79637690-1b897d80-819f-11ea-8973-84e3b7bb6821.png)
these are names you have put in the frontend

![image](https://user-images.githubusercontent.com/28673959/79637703-378d1f00-819f-11ea-983f-6f8d7c2bc698.png)
these are the subject names in the database. That is why the book is not getting added.. remove the hardcoded ones and load the subject names from the backend

**Comment by Nethmi96** [comment]
I'll change it

**Comment by Nethmi96** [comment]
Solved!

**Comment by Nethmi96** [comment]
Although the book is adding successfully when it's not get added to the book list. 
When i checked database it can be seen that book has been added to the database successfully.
![image](https://user-images.githubusercontent.com/44530828/79700289-457f9480-82b2-11ea-9525-f16b33c7b922.png)

No  end point **8080/shareabook/api/v1/book/all:1** is not working at any place in my platform :( Not even in the admin dashboard when i tried to get all the books uploaded to the system.
![image](https://user-images.githubusercontent.com/44530828/79700316-73fd6f80-82b2-11ea-9eeb-4958999e9d6e.png)

This is the error I'm getting in the console.
![image](https://user-images.githubusercontent.com/44530828/79700325-84ade580-82b2-11ea-86b8-648957fc081b.png)

**Comment by dilinipeirs** [comment]
this error is resolved.
The error was in the backend. The book adding was not 100% successful. That was why an error came up when retrieving book data from the database. Those are corrected now and the book is added to the dashboard. Therefore please check if it is working in yours.

**There were slight changes done to the dataset and the database. Therefore please drop the database and put the dummy data again.**

**However another error came up.**

Adding a used book is working fine and it gets added to the dashboard as well.
But when trying to add a **brand new** book, the request doesnt even come to the backend.. therefore i am having a hard time figuring out what is wrong.

this is a screenshot of the response i get when trying to add a **brand new** book. Nothing is returned from the backend since the backend doesnt get the request. Therefore please look into this
![image](https://user-images.githubusercontent.com/28673959/79701301-921a9e00-82b9-11ea-8872-54c6c9388237.png)

**Comment by dilinipeirs** [comment]
please note the reopened issue **'retrieving book data from backend'** for the changes made to the object structure and send the book details accordingly

**Comment by Nethmi96** [comment]
The mentioned issue is solved. It was a frontend error occured since I've put fields such as stream, subject, exam type, state etc. as required eventhough they are not required when the product type is a story book or an educational publication as well as condition is not asked when the state is brand new. I've fixed that error, and also, did necessary changes to the front end according to the new object structure. 
Eventhough adding **Study materials** to the system is fine I'm getting an error when trying to add a story book.
This is the error i got when trying to add **Story Book** to the platform
![image](https://user-images.githubusercontent.com/44530828/79751746-bcf40900-8330-11ea-81a5-ac5aa44f9e0e.png)
![image](https://user-images.githubusercontent.com/44530828/79751762-c1202680-8330-11ea-89c9-e06ae28fe861.png)

**Comment by dilinipeirs** [comment]
the error is resolved.

now the add book works fine 90%. have to check with grade6-9 books after getting the dummy data
