### ISSUE TITLE
Admin Profile enhacements

### ISSUE THREAD

**Issue by Nethmi96** [bitsoferised/ShareABook_Frontend_v.2#18]
Although user profile edit works fine, when I'm trying to edit admin profile an **status code 500** error occurs.
![image](https://user-images.githubusercontent.com/44530828/79847849-ed45b100-83dd-11ea-849e-9315104b6909.png)

Console error is as follows.
![image](https://user-images.githubusercontent.com/44530828/79847973-15cdab00-83de-11ea-8c39-7a1b9405cb2a.png)

**Comment by dilinipeirs** [comment]
this error came because the email was not present in the data you sent on the updated details..

![image](https://user-images.githubusercontent.com/28673959/79913370-18152100-8441-11ea-866a-91e3e99a8247.png)

since it is not changable for the users, ive changed the logic in the backend to cater that.. so its resolved now.

please do the following changes..
1. confirmation alerts on success or failure
2. im sending the user registered date in the **createdOn** field.. so u can show this in the profile details as well... (for all the user types)
