### ISSUE TITLE
Donations Frontend UI and functionalities

### ISSUE THREAD

**Issue by Nethmi96** [bitsoferised/ShareABook_Frontend_v.2#26]
There should be two separate donation forms for those who have not registered with the platform and those who already have an account.

**Comment by Nethmi96** [comment]
@dilinipeirs did you start developing backend part for this?

**Comment by dilinipeirs** [comment]
why should there be 2 forms?

you can do that as in feedback process right?

nope i havent done the backend part yet. will do it soon

**Comment by dilinipeirs** [comment]
@Nethmi96 here is the donation process i came up with. please check whether u can do this

![image](https://user-images.githubusercontent.com/28673959/82758571-ebb84000-9e04-11ea-83e4-22d0909e81e5.png)

![image](https://user-images.githubusercontent.com/28673959/82758578-efe45d80-9e04-11ea-8421-a44e930eb057.png)

![image](https://user-images.githubusercontent.com/28673959/82758580-f2df4e00-9e04-11ea-8e0b-c546f6ed7044.png)

**Comment by dilinipeirs** [comment]
*mistake in writing

in the above 2nd photo, the tool tip should contain *Dont worry we _won't_ bother you other than that.*

**Comment by Nethmi96** [comment]
yeah the given process can be done. But we might need to get customer's mobile number as well in order integrate ipg.
Mobile number is a required data in that ipg.
also we need a reference number for individual donation

**Comment by dilinipeirs** [comment]
it is not practical to ask for the mobile number right?
what if you put a default phone number for that? which is valid but easily identified as a dummy phone number?

as for the ref. number, it is not practical to go to the backend and get a reference number as in the order process. Because compared to placing an order, the data exchanged in this process is really less. Therefore, can u dynamically generate a 6 or 8 character long random string from the frontend and use that as the ref.? Then u can send that ref. to the backend when sending the details..

**Comment by dilinipeirs** [comment]
endpoints are made
