### ISSUE TITLE
Issue in getting all student details

### ISSUE THREAD

**Issue by Nethmi96** [bitsoferised/ShareABook_Frontend_v.2#45]
An error occurred in getting all student details for the admin panel.
![image](https://user-images.githubusercontent.com/44530828/82073013-35fb3c00-96f6-11ea-8c7e-2184bacf4345.png)

Console error is as follows
![image](https://user-images.githubusercontent.com/44530828/82073081-56c39180-96f6-11ea-8899-a48147f0a6fb.png)
![image](https://user-images.githubusercontent.com/44530828/82073086-5a571880-96f6-11ea-9220-7a5e29fcaf38.png)

**Comment by dilinipeirs** [comment]
There has been a mix up in the screenshots u have provided. The frontend console error screenshot and the 3rd screenshot goes together and that is not an issue in getting student details.. the endpoint u have used in the 1st screenshot (http://localhost:8080/shareabook/api/v1/admin/dashboard/data) is to get the data needed for the dashboard of the admin.

only the 2nd screenshot is what tallies with the topic of the issue. -> this error was caused because one user was not registered successfully.. dunno why this happened 😥😥 ive corrected it manually for now. inform me if this happens again.

**FYI - Make sure you dont use the same email address to make admin and student accounts because, it is the email that we use as the id kindof thing in the system**

anyhow, both the errors shown here are resolved now.
