### ISSUE TITLE
User should not be able to purchase their own books

### ISSUE THREAD

**Issue by dilinipeirs** [bitsoferised/ShareABook_Frontend_v.2#49]
As of now, we are not doing any verification of the user when sending the books to the user Dashboard.. 

This should be verified as the user should not be able to purchase their own books.. but should be able to see how their books are displayed in the dashboard.

My suggestion is to send the user each time an endpoint is called to retrieve books for selling in the frontend.. so that, a new field can be added to the book object saying **isSeller** or something like that..

If **isSeller** is **true**, the add to cart icon **should not be shown**. Else it is displayed

**Comment by dilinipeirs** [comment]
This task is somehow affecting alot of endpoints that gets called from the user dashboard.

Please comment your ideas

**Comment by Nethmi96** [comment]
yeah the proposed solution is good. But in order to do that i have to send the user details when retrieving books right?
So, how about without sending isSeller, sending something like *userID* or something related to the seller? So, in the frontend I can check that details with user details and make the cart icon disable or something.

**Comment by dilinipeirs** [comment]
ok. ill send the **sellerID**

**Comment by dilinipeirs** [comment]
sellerID is sent now with the book details. @Nethmi96 please make necessary changes in the frontend as discussed

**Comment by Nethmi96** [comment]
done
