### ISSUE TITLE
Product View

### ISSUE THREAD

**Issue by Nethmee** [bitsoferised/ShareABook_Frontend_v.2#62]
The carousel of the product display only showed me one picture.

**Comment by Nethmi96** [comment]
That's not because of a problem in the image slider.
Some products only have one picture and for some products there is some problem in saving images due to some bug in the photo upload algorithm (according to dilini for products which have images greater than size 200kb as i can remember)
check last harry potter product in page 4, it has 3 images and image slider is working fine.

**Comment by dilinipeirs** [comment]
yes this is related to that image compression algorithm

**Comment by dilinipeirs** [comment]
to be handled from backend issue #109

**Comment by dilinipeirs** [comment]
refer backend issue #104 for the solution
