### ISSUE TITLE
Save and update seller billing details

### ISSUE THREAD

**Issue by Nethmi96** [bitsoferised/ShareABook_Frontend_v.2#72]
@dilinipeirs please comment your thoughts on this

**Comment by dilinipeirs** [comment]
please use the naming as 'Seller account details' or something of that sort when u create the UI.. the word 'Billing' can be misunderstood as credit card details..

Since it is not practical to ask for account details upon user registration, we can maybe check whether the account details are added when a user tries to add a book..

so i can create an endpoint to check whether account details are there.
   -> if there are, then no problem
   -> if no account details are added, u can direct the user to form to add the account details first, and then add their book to the system..

something like that?

so its like, unless the user has not added their account details to the system, we dont let them add books.. because theres no point.

if this idea is good. i can proceed to making the endpoints

**Comment by Nethmi96** [comment]
Yeah, that method sounds good.
Inform me after end point are done

**Comment by dilinipeirs** [comment]
The endpoints are in progress. 
But i have mentioned the structure in the API doc - under authentication table..

use them to create the frontend.. after i finished developing, you or @Nethmee can do the testing to see if it works

**Comment by dilinipeirs** [comment]
the endpoints are implemented.

please do the testing

**Comment by dilinipeirs** [comment]
issue in removing bank details resolved
