### ISSUE TITLE
Forgot password

### ISSUE THREAD

**Issue by Nethmee** [bitsoferised/ShareABook_Frontend_v.2#85]
![reset pw error](https://user-images.githubusercontent.com/40081010/83454462-db920780-a479-11ea-8f8b-4ac4a250520d.PNG)
When I entered the email address and click the  reset password button , it takes me nowhere.

![reset pw error2](https://user-images.githubusercontent.com/40081010/83454602-0d0ad300-a47a-11ea-83af-a133bfdffaad.PNG)

**Comment by dilinipeirs** [comment]
the error is not in the backend. 

![image](https://user-images.githubusercontent.com/28673959/83801669-29e81600-a6c7-11ea-8ede-4c1e29740788.png)

previously the endpoint accepted the email as a request parameter. since it doesnt make sense to take the email from a request param in a POST request, it was modified.

this was missed after the modifications were done.

@Nethmi96 please look into this. the API doc is updated
